namespace: acrpull
image: ghcr.io/ghcr.io/thegunner295/msi-acrpull
replicas: 2
nodeSelector: {}
tolerations: []
affinity: {}
ttlRotationFraction: 0.5
kubeAPIQPS: 20
kubeAPIBurst: 30
allowedACRServerSuffixes:
  - azurecr.io
