name: Publish

on:
  push:
    branches: main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set lower-case image name
      id: image
      run: echo "name=${REPO,,}" >> "$GITHUB_OUTPUT"
      env:
        REPO: ${{ github.repository }}

    - name: Log in to the Container registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
      with:
        images: ${{ env.REGISTRY }}/${{ steps.image.outputs.name }}
        tags: |
          type=semver,pattern={{version}}
          type=raw,value=${{ github.ref_name }}-build.${{ github.run_number }}
    - name: Set image variables
      run: |
        echo "IMG=${{ env.REGISTRY }}/${{ steps.image.outputs.name }}" >> $GITHUB_ENV
        echo "IMG_TAG=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV
    - name: Build the Docker Image
      run: make docker-build

    - name: Push to ghcr.io
      run: make docker-push
